# Generated by Django 3.0.7 on 2020-06-19 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField()),
                ('y_value', models.FloatField()),
                ('group', models.CharField(max_length=64)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrol_panel.Plot')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrol_panel.Session'),
        ),
    ]
