# Generated by Django 3.0.7 on 2020-06-25 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol_panel', '0002_plot_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=datetime.datetime(2020, 6, 25, 15, 29, 33, 684078), verbose_name='date added')),
                ('value', models.ImageField(upload_to='')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrol_panel.Plot')),
            ],
        ),
    ]
