# Generated by Django 3.0.7 on 2020-06-25 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol_panel', '0003_imagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 19, 54, 20, 340798), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='value',
            field=models.ImageField(upload_to='uploaded/images'),
        ),
    ]
