# Generated by Django 3.0.7 on 2020-06-25 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol_panel', '0004_auto_20200625_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 3, 43, 700956), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.IntegerField(choices=[(1, 'Type Line'), (2, 'Type Scatter'), (3, 'Type Image')]),
        ),
    ]
