# Generated by Django 3.0.7 on 2020-06-25 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol_panel', '0005_auto_20200625_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(0, 'Status Not Started'), (1, 'Status Running'), (2, 'Status Done')], default=0),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 10, 8, 81282), verbose_name='date added'),
        ),
    ]
