# Generated by Django 3.0.7 on 2020-06-25 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol_panel', '0006_auto_20200625_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='millis_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 53, 25, 874695), verbose_name='date added'),
        ),
    ]
