# Generated by Django 3.0.7 on 2020-06-25 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol_panel', '0007_auto_20200625_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 59, 25, 800117), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='session',
            name='millis_left',
            field=models.BigIntegerField(default=0),
        ),
    ]
