# Generated by Django 3.0.7 on 2020-06-25 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol_panel', '0008_auto_20200625_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 0, 12, 49, 276015), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='session',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 0, 12, 49, 275020), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='session',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 0, 12, 49, 275020), verbose_name='date updated'),
        ),
    ]
